name: Build

on: [push, pull_request]

jobs:
  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build with Maven
        run: |
          cd coffeeshop-service
          mvn -B clean install -Pnative -Dquarkus.native.container-build=true

